CREATE OR REPLACE TRIGGER INSIS_BLC_GLOBAL_CUST.BLC_ACCOUNT_GEN_UPD_TRG 
 BEFORE
  UPDATE
 ON INSIS_BLC_GLOBAL_CUST.BLC_ACCOUNT_GEN
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.UPDATED_ON := SYSDATE;
    :NEW.UPDATED_BY := insis_context.get_user;
END;
/
CREATE OR REPLACE TRIGGER INSIS_BLC_GLOBAL_CUST.BLC_ACCOUNT_ACC_UPD_TRG 
 BEFORE
  UPDATE
 ON INSIS_BLC_GLOBAL_CUST.BLC_ACCOUNT_ACC
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.UPDATED_ON := SYSDATE;
    :NEW.UPDATED_BY := insis_context.get_user;
END;
/
CREATE OR REPLACE TRIGGER INSIS_BLC_GLOBAL_CUST.BLC_CLAIM_GEN_UPD_TRG 
 BEFORE
  UPDATE
 ON INSIS_BLC_GLOBAL_CUST.BLC_CLAIM_GEN
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.UPDATED_ON := SYSDATE;
    :NEW.UPDATED_BY := insis_context.get_user;
END;
/
CREATE OR REPLACE TRIGGER INSIS_BLC_GLOBAL_CUST.BLC_CLAIM_ACC_UPD_TRG 
 BEFORE
  UPDATE
 ON INSIS_BLC_GLOBAL_CUST.BLC_CLAIM_ACC
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.UPDATED_ON := SYSDATE;
    :NEW.UPDATED_BY := insis_context.get_user;
END;
/
CREATE OR REPLACE TRIGGER INSIS_BLC_GLOBAL_CUST.BLC_PROFORMA_GEN_UPD_TRG 
 BEFORE
  UPDATE
 ON INSIS_BLC_GLOBAL_CUST.BLC_PROFORMA_GEN
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.UPDATED_ON := SYSDATE;
    :NEW.UPDATED_BY := insis_context.get_user;
END;
/
CREATE OR REPLACE TRIGGER INSIS_BLC_GLOBAL_CUST.BLC_PROFORMA_ACC_UPD_TRG 
 BEFORE
  UPDATE
 ON INSIS_BLC_GLOBAL_CUST.BLC_PROFORMA_ACC
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.UPDATED_ON := SYSDATE;
    :NEW.UPDATED_BY := insis_context.get_user;
END;
/
CREATE OR REPLACE TRIGGER INSIS_BLC_GLOBAL_CUST.BLC_REI_GEN_UPD_TRG 
 BEFORE
  UPDATE
 ON INSIS_BLC_GLOBAL_CUST.BLC_REI_GEN
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.UPDATED_ON := SYSDATE;
    :NEW.UPDATED_BY := insis_context.get_user;
END;
/
CREATE OR REPLACE TRIGGER INSIS_BLC_GLOBAL_CUST.BLC_REI_ACC_UPD_TRG 
 BEFORE
  UPDATE
 ON INSIS_BLC_GLOBAL_CUST.BLC_REI_ACC
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    :NEW.UPDATED_ON := SYSDATE;
    :NEW.UPDATED_BY := insis_context.get_user;
END;

