DELETE
  FROM INSIS_GEN_BLC_V10.BLC_LOOKUPS
WHERE LOOKUP_SET = 'TRANSACTION_TYPES'
    AND LOOKUP_CODE = 'MANUAL_PREMIUM_ADJ';

DELETE
  FROM INSIS_GEN_BLC_V10.BLC_LOOKUPS
WHERE LOOKUP_SET = 'DOC_OPEN_REASONS'
    AND LOOKUP_CODE = 'CHANGE_DUE_DATE';

DELETE
  FROM INSIS_GEN_BLC_V10.BLC_ACTIONS
WHERE REASON_ID IN (
                                        SELECT LOOKUP_ID
                                          FROM INSIS_GEN_BLC_V10.BLC_LOOKUPS
                                        WHERE LOOKUP_SET = 'DOC_OPEN_REASONS'
                                            AND LOOKUP_CODE = 'OPEN_DOCUMENT'
                                        );

DELETE
  FROM INSIS_GEN_BLC_V10.BLC_LOOKUPS
WHERE LOOKUP_SET = 'DOC_OPEN_REASONS'
    AND LOOKUP_CODE = 'OPEN_DOCUMENT';

UPDATE INSIS_GEN_BLC_V10.BLC_SLA_ACC_RULES SET WHERE_CLAUSE = 'bt_transaction_type = "PREMIUM"'
WHERE ACC_RULE_ID = 1000;

DELETE
  FROM INSIS_GEN_BLC_V10.BLC_SETTINGS
WHERE SETTING = 'CustManualTrxMaxAmount';

DELETE
  FROM INSIS_GEN_BLC_V10.BLC_VALUES
WHERE SETTING = 'CustManualTrxMaxAmount';

DELETE
  FROM INSIS_SYS_V10.SRV_EVENT_FUNCTION
WHERE EVENT_ID = 'CREATE_BLC_TRANSACTION'
    AND FUNCTION_NAME = 'INSIS_BLC_GLOBAL_CUST.srv_cust_bo.ValidateNewAdjTrx';

DELETE
  FROM INSIS_SYS_V10.SRV_EVENT_FUNCTION
WHERE EVENT_ID = 'MODIFY_BLC_TRANSACTION'
    AND FUNCTION_NAME = 'INSIS_BLC_GLOBAL_CUST.srv_cust_bo.ValidateNewAdjTrx';

DELETE
  FROM INSIS_SYS_V10.SRV_EVENT_FUNCTION
WHERE EVENT_ID = 'MODIFY_BLC_DOCUMENT'
    AND FUNCTION_NAME = 'INSIS_BLC_GLOBAL_CUST.srv_cust_bo.SetModifyTrxYes';

DELETE
  FROM INSIS_SYS_V10.SRV_MESSAGES
WHERE MSG_ID = 'cust_billing_pkg.VCT.ErrAmnt';

COMMIT;