--Ejecutar uno por uno.
CREATE INDEX INSIS_BLC_GLOBAL_CUST.BLC_PROFORMA_ACC_IDX_01 ON INSIS_BLC_GLOBAL_CUST.BLC_PROFORMA_ACC(ACC_TEMP_CODE,DR_CR_FLAG) TABLESPACE INDX;
----
----
CREATE INDEX INSIS_BLC_GLOBAL_CUST.BLC_PROFORMA_GEN_IDX_02 ON INSIS_BLC_GLOBAL_CUST.BLC_PROFORMA_GEN(LTRIM("DOC_NUMBER",'0'),ABS("DOC_AMOUNT")) TABLESPACE INDX;
